program: sweep_baseline.py
name: sweep_baseline_calibration_study
project: CalibrationStudy
method: grid
parameters:
  targetid: 
    values: [240, 340, 1951]
  epoch_number: 
    values: [400]
  batch_size: 
    values: [200]
  nr_models: 
    values: [10]
  learning_rate:
    values: [1e-5, 1e-4, 1e-3, 1e-2, 0.1]
  weight_decay:
    values: [1e-5, 1e-4, 1e-3, 1e-2, 0.1]
  hidden_sizes:
    values: [4,5,6,7,8,9,10,15,20,25,30]
  dropout:
    values: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
 

